name: Tutorial
version: '${project.version}'
main: dev.bence.tutorial.Tutorial
api-version: 1.18

commands:
  heal:
    description: Speler wordt geheald.
    aliases: [genees]
  geef:
    description: Geef commando
    aliases: [give]
  kit:
    description: geef kit jezelf
  menu:
    description: opent een gui
  stats:
    description: hier kun jij je stats ziene
  vlieg:
    description: zet vliegen aan of uit
  gamemodes:
    description: Switch gamemode
  selector:
    description: selector
